### ISSUE TITLE
More complex system of assigning roles

### ISSUE THREAD

**Issue by TiBarification** [KarlOfDuty/SCPDiscord#175]
Propositon to have instead of https://github.com/KarlOfDuty/SCPDiscord/blob/main/SCPDiscordPlugin/config.yml#L95

to use structure as root of the tree only 1 pass, and infinite passes to childrens.

```
rolesync:
    80:  # Admin (80 - is position of execution)
        # logic-types can be:
        # 0: None (disables logic for this role), we never go here and commands not executed.
        # 1: And
        # 2: Or
        # 3: Not And
        # 4: Primary Only
        # 5: Xor (exclusive or)
        # 6: Not Or
        type: 1
        roles: [1194372610029531267]
        commands: []
        children:
            100:
                type: 1
                roles: 
                - 1182086202770337842
                commands:
                - "sp setgroup <var:player-id> moneybagplus"
                children: {}
            101:
                type: 1
                roles: 
                - 1136640371716276245
                commands:
                - "sp setgroup <var:player-id> moneybag"
                children: {}
    90:  # Senior Moderator
        # logic-types can be:
        # 0: None (disables logic for this role)
        # 1: And
        # 2: Or
        # 3: Not And
        # 4: Primary Only
        # 5: Xor (exclusive or)
        # 6: Not Or
        type: 1
        roles: [1122886150886010982]
        commands:
        - "scpd grantvanillarank <var:player-userid> seniormoderator"
        - "scpd grantreservedslot <var:player-userid> <var:discordusername> (<var:discordid>)"
        children:
            100:
                type: 1
                roles: 
                - 1182086202770337842
                commands:
                - "sp setgroup <var:player-id> tester"
                children: {}
            101:
                type: 1
                roles: 
                - 1136640371716276245
                commands:
                - "sp setgroup <var:player-id> tester2"
                children: {}
```

Another proposal is to ignore from grantvanillarank users explicitly having group in config_remoteadmin.txt
