### ISSUE TITLE
RoleSync Module not working as intended

### ISSUE THREAD

**Issue by Unbistrackted** [KarlOfDuty/SCPDiscord#191]
![image](https://github.com/user-attachments/assets/f313cd19-45c4-4ce0-afe4-21d77c38e0cd)

Config file:  
 ```
# Whether to use the rolesync system.
    rolesync: true

    # Whether to track players play time on the server, which can then be checked using the /playerinfo command.
    playtime: true

    # Whether files should be read from the global config directory or the local one (aka the server specific one).
    useglobaldirectory:
        language: true
        rolesync: true
        mutes: true
        playtime: true

    # Always replace language and emote files when the plugin starts (does not affect overrides.yml and emote-overrides.yml).
    # Turn this off if you will be directly editing the language files.
    # If you are only making small edits to the language files it is highly
    # recommended to use overrides.yml instead of editing the language file.
    regeneratelanguagefiles: true

    # Whether SCPDiscord should automatically cause the game to reload certain files when they are changed by other servers.
    autoreload:
        reservedslots: true
        whitelist: false

# Sets commands to run whenever someone with a synced Discord rank joins the server,
# only the highest command in the list that matches the player is executed.
# Turn on debug above to see console feedback when the commands are used.
# Valid variables:
# player-userid
# player-id
# player-name
# player-ipaddress
# discord-displayname
# discord-username
# discord-userid
# There are some more player variables you can use here, but they are mostly irrelevant, check the list in APIExtensions.cs on GitHub for the full list.
rolesync:
    - "1312965374345482251":
        - "scpd grantvanillarank <var:player-userid> ds"
        - "scpd grantreservedslot <var:player-userid> @<var:discordusername> (<var:discordid>)"
        - "/pbc <var:player-id> 3 TESTE."

    - "1313693703759728803":
        - "scpd grantvanillarank <var:player-userid> da"
        - "scpd grantreservedslot <var:player-userid> @<var:discordusername> (<var:discordid>)"
        - "/pbc <var:player-id> 5 Obrigado por doar! Você agora tem direito a Slot Reservado e consegue ver o Chat de admin dentro do jogo."

    - "1313982288974839858":
        - "scpd grantvanillarank <var:player-userid> bo"
        - "scpd grantreservedslot <var:player-userid> @<var:discordusername> (<var:discordid>)"
        - "/pbc <var:player-id> 5 Obrigado por dar boost em nosso servidor do discord! Você agora tem direito a Slot Reservado!"

```
